In [0]:
import os
####*注意start*: その一行をtensorflowインポートする前に置く
os.environ['PYTHONHASHSEED']=str(1)
####*注意end*

# for irisデータ
from sklearn import datasets
from sklearn.model_selection import train_test_split

# for ニューラルネットワーク
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

import tensorflow as tf
import numpy as np
import random
print("tensorflowのバージョン：", tf.__version__)

def reset_random_seeds():
   os.environ['PYTHONHASHSEED']=str(1)
   tf.random.set_seed(1)
   np.random.seed(1)
   random.seed(1)

reset_random_seeds()

tensorflowのバージョン： 2.2.0-rc4


In [0]:
# irisデータをロード
iris = datasets.load_iris()
X = iris.data
y = iris.target

# trainデータとvalidationデータ、testデータを作成
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=0,
                                                    stratify=y)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train,
                                                  test_size=0.1,random_state=1,
                                                  stratify=y_train)
print("X_train:", X_train)
print("y_train:", X_train)
print("X_test:", X_test)
print("y_test:", y_test)

X_train: [[5.5 2.3 4.  1.3]
 [6.5 3.  5.5 1.8]
 [4.8 3.4 1.6 0.2]
 [6.3 2.3 4.4 1.3]
 [5.2 3.4 1.4 0.2]
 [5.4 3.4 1.7 0.2]
 [6.  2.9 4.5 1.5]
 [7.9 3.8 6.4 2. ]
 [7.7 3.8 6.7 2.2]
 [5.  3.2 1.2 0.2]
 [6.6 2.9 4.6 1.3]
 [5.4 3.9 1.3 0.4]
 [5.2 3.5 1.5 0.2]
 [5.4 3.7 1.5 0.2]
 [5.6 2.7 4.2 1.3]
 [5.8 2.8 5.1 2.4]
 [4.6 3.6 1.  0.2]
 [6.1 2.8 4.  1.3]
 [4.3 3.  1.1 0.1]
 [5.  3.  1.6 0.2]
 [6.1 2.8 4.7 1.2]
 [4.7 3.2 1.6 0.2]
 [6.3 2.5 4.9 1.5]
 [5.7 2.9 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [6.  2.2 5.  1.5]
 [5.  3.5 1.6 0.6]
 [7.2 3.2 6.  1.8]
 [5.5 2.4 3.8 1.1]
 [5.2 4.1 1.5 0.1]
 [6.3 2.5 5.  1.9]
 [5.9 3.2 4.8 1.8]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 5.6 2.4]
 [6.  3.  4.8 1.8]
 [5.  3.3 1.4 0.2]
 [5.2 2.7 3.9 1.4]
 [4.7 3.2 1.3 0.2]
 [6.  2.2 4.  1. ]
 [7.7 2.8 6.7 2. ]
 [4.9 3.1 1.5 0.2]
 [5.4 3.  4.5 1.5]
 [6.4 2.8 5.6 2.2]
 [6.7 3.  5.  1.7]
 [6.4 2.9 4.3 1.3]
 [6.4 3.2 5.3 2.3]
 [6.9 3.1 4.9 1.5]
 [6.6 3.  4.4 1.4]
 [6.9 3.1 5.1 2.3]
 [7.6 3.  6.6 2.1]
 [5.8 2.7 3.9 1.2]
 [5.7 3.8 1.7 0.3]
 [5

In [0]:
# ニューラルネットワークを作成
# 定数
input_size = 4
hidden_size = 10
output_size = 3 # 3種類
batch_size = 32
epoch_size = 100
save_path = 'simple_NN_model.hdf5'

input_size = 4 # 4個の特徴量
hidden_size = 10
output_size = 3 # 3種類のアヤメ

batch_size = 32
epoch_size = 500
save_path = 'simple_NN_model.hdf5'

model = Sequential()
model.add(Dense(hidden_size, activation='relu', input_dim=input_size))
model.add(Dense(output_size, activation='softmax'))

# 訓練の継続条件：
# ①何epoch(patience)訓練しても、モデルの精度が上がらなければ訓練を終了
earlyStop = EarlyStopping(monitor='val_accuracy', verbose=1, patience=64)
# ②モデル保存の条件
# 一番精度が良いcheckpointを保存
saveBestModel = ModelCheckpoint(filepath=save_path, monitor='val_loss',
                                verbose=1, save_best_only=True)

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=epoch_size, batch_size=batch_size,
            validation_data=(X_val,y_val), callbacks=[earlyStop, saveBestModel])

Epoch 1/500
1/3 [=========>....................] - ETA: 0s - loss: 1.0741 - accuracy: 0.3438
Epoch 00001: val_loss improved from inf to 0.93040, saving model to simple_NN_model.hdf5
3/3 [==============================] - 0s 71ms/step - loss: 1.0527 - accuracy: 0.3298 - val_loss: 0.9304 - val_accuracy: 0.3636
Epoch 2/500
1/3 [=========>....................] - ETA: 0s - loss: 1.1240 - accuracy: 0.2500
Epoch 00002: val_loss improved from 0.93040 to 0.89361, saving model to simple_NN_model.hdf5
3/3 [==============================] - 0s 16ms/step - loss: 1.0042 - accuracy: 0.3298 - val_loss: 0.8936 - val_accuracy: 0.3636
Epoch 3/500
1/3 [=========>....................] - ETA: 0s - loss: 0.8866 - accuracy: 0.4062
Epoch 00003: val_loss improved from 0.89361 to 0.86169, saving model to simple_NN_model.hdf5
3/3 [==============================] - 0s 15ms/step - loss: 0.9564 - accuracy: 0.3298 - val_loss: 0.8617 - val_accuracy: 0.3636
Epoch 4/500
1/3 [=========>....................] - ETA: 0s - l

In [0]:
# 予測

# 一番良いモデルをロード
model = load_model(save_path)

y_pred = np.argmax(model.predict(X_test),axis=1)
print(y_pred)
print(y_test)

# テストデータのロスと正解率
model.evaluate(X_test, y_test)

[2 2 0 0 1 0 1 2 0 1 0 2 0 2 1 2 1 1 1 0 1 2 0 1 2 2 2 2 1 2 1 0 0 1 1 2 1
 0 0 1 0 2 0 0 2]
[2 2 0 0 1 0 1 2 0 1 0 2 0 2 1 2 1 1 1 0 1 2 0 1 2 2 2 2 1 2 1 0 0 1 1 2 1
 0 0 1 0 2 0 0 2]
2/2 [==============================] - 0s 2ms/step - loss: 0.3438 - accuracy: 1.0000


[0.34377583861351013, 1.0]